name: CI to test the deploy-clojars action

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  deploy-clojars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get an env
        uses: yetanalytics/action-setup-env@v1
      
      - name: Test deployment
        uses: yetanalytics/action-deploy-clojars@v1.1.0-SNAPSHOT
        with:
          artifact-id: 'action-deploy-clojars'
          version: 'LATEST'
          resource-dirs: '[]'
          publish: 'true'
          clojars-username: ${{ secrets.CLOJARS_USERNAME }}
          clojars-deploy-token: ${{ secrets.CLOJARS_PASSWORD }}
