name: CI to test the deploy-clojars action

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  deploy-clojars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get an env
        uses: yetanalytics/action-setup-env@v1
      
      - name: Test deployment
        uses: yetanalytics/action-deploy-clojars@v1
        with:
          artifact-id: 'actions'
          version: 'LATEST'
          resource-dirs: '[]'
          publish: 'false'
          # We're not actually publishing to Clojars so use dummy values
          clojars-username: 'foo'
          clojars-deploy-token: 'bar'

